// frontend/routes/register/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import type { RegisterRequest, AuthUser } from "~/types/gen";
  import { setUser } from "$lib/state";
  import { API_URL } from "$lib/api";

  let name = $state("");
  let email = $state("");
  let password = $state("");

  function register() {
    if (!name || !email || !password) return;

    fetch(API_URL + "/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ name, email, password } satisfies RegisterRequest),
    })
    .then((res) => res.json())
    .then((data: AuthUser) => {
      localStorage.setItem("JWT_TOKEN", data.token);

      setUser(data.public_user);

      goto("/");
    });
  }

  $effect(() => {
    if (localStorage.getItem("JWT_TOKEN")) {
      goto("/");
    }
  });
</script>

<div class="flex justify-center pt-32">
  <article class="bg-[#0f0f0f] px-6 py-4 rounded-xl w-[max(22vw,330px)]">
    <h2 class="text-sm text-center">Sign up to Robo</h2>

    <section class="mt-4 flex flex-col gap-2 *:bg-white/10 *:rounded-lg *:px-4 *:py-2">
      <input bind:value={name} type="text" placeholder="your name"/>
      <input bind:value={email} type="email" placeholder="you@mail.com"/>
      <input bind:value={password} type="password" placeholder="passw0rd"/>
    </section>

    <section class="flex justify-between items-center mt-6">
      <a href="/login" class="hover:underline">
        Already have an account?
      </a>

      <button
        class="rounded-lg px-4 py-2 bg-blue-500"
        onclick={register}
      >
        Sign up
      </button>
    </section>
  </article>
</div>

// frontend/src/app/register/page.tsx
"use client";

import Link from 'next/link';
import { useRegisterMutation } from './_api';
import { useCurrentUser } from "~/current-user";
import { redirect } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { RegisterRequest } from '~/types/gen';

export default function RegisterPage() {
  const registerMutation = useRegisterMutation();
  const currentUser = useCurrentUser();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterRequest>();

  function onSubmit(data: RegisterRequest) {
    registerMutation.mutate(data);
  }

  if (registerMutation.isSuccess) {
    currentUser.set(registerMutation.data);
    redirect("/");
  }

  return (
    <div className="flex justify-center pt-32">
      <form
        onSubmit={handleSubmit(onSubmit)}
        className="bg-[#0f0f0f] px-6 py-4 rounded-xl w-[max(22vw,330px)]"
      >
        <h2 className="text-sm text-center">Sign up to Robo</h2>

        <section className="mt-4 flex flex-col gap-2 *:bg-white/10 *:rounded-lg *:px-4 *:py-2">
          <input
            {...register("name", { required: true, minLength: 3, maxLength: 99 })}
            aria-invalid={!!errors.name}
            type="text"
            placeholder="your name"
            className="aria-[invalid=true]:bg-red-500"
          />

          <input
            {...register("email", { required: true, minLength: 3, maxLength: 99 })}
            aria-invalid={!!errors.email}
            type="email"
            placeholder="you@mail.com"
            className="aria-[invalid=true]:bg-red-500"
          />

          <input
            {...register("password", { required: true, minLength: 8, maxLength: 99 })}
            aria-invalid={!!errors.password}
            type="password"
            placeholder="passw0rd"
            className="aria-[invalid=true]:bg-red-500"
          />
        </section>

        <section className="flex justify-between items-center mt-6">
          <Link href="/signin" className="hover:underline">
            Already have an account?
          </Link>

          <button
            type="submit"
            className="rounded-lg px-4 py-2 bg-blue-500"
          >
            Sign up
          </button>
        </section>
      </form>
    </div>
  );
}
